package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisCropOtherShareholderIf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGISTER_DEPARTMENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registerDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributiveFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributivePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.SN_NO
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.SN_NO
     *
     * @param snNo the value for CIS_CROP_OTHER_SHAREHOLDER_IF.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.ID
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.ID
     *
     * @param id the value for CIS_CROP_OTHER_SHAREHOLDER_IF.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.APPLY_NO
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.APPLY_NO
     *
     * @param applyNo the value for CIS_CROP_OTHER_SHAREHOLDER_IF.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_NAME
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropName() {
        return cropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_NAME
     *
     * @param cropName the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropName(String cropName) {
        this.cropName = cropName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_NO
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegistNo() {
        return registNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_NO
     *
     * @param registNo the value for CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistNo(String registNo) {
        this.registNo = registNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropType() {
        return cropType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE
     *
     * @param cropType the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropType(String cropType) {
        this.cropType = cropType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE_DESC
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropTypeDesc() {
        return cropTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE_DESC
     *
     * @param cropTypeDesc the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropTypeDesc(String cropTypeDesc) {
        this.cropTypeDesc = cropTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_FUND
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegistFund() {
        return registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_FUND
     *
     * @param registFund the value for CIS_CROP_OTHER_SHAREHOLDER_IF.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistFund(String registFund) {
        this.registFund = registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatus() {
        return cropStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS
     *
     * @param cropStatus the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatus(String cropStatus) {
        this.cropStatus = cropStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS_DESC
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatusDesc() {
        return cropStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS_DESC
     *
     * @param cropStatusDesc the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatusDesc(String cropStatusDesc) {
        this.cropStatusDesc = cropStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGISTER_DEPARTMENT
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.REGISTER_DEPARTMENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegisterDepartment() {
        return registerDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.REGISTER_DEPARTMENT
     *
     * @param registerDepartment the value for CIS_CROP_OTHER_SHAREHOLDER_IF.REGISTER_DEPARTMENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegisterDepartment(String registerDepartment) {
        this.registerDepartment = registerDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_FUND
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributiveFund() {
        return contributiveFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_FUND
     *
     * @param contributiveFund the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributiveFund(String contributiveFund) {
        this.contributiveFund = contributiveFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_PERCENT
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributivePercent() {
        return contributivePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_PERCENT
     *
     * @param contributivePercent the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributivePercent(String contributivePercent) {
        this.contributivePercent = contributivePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CURRENCY
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CURRENCY
     *
     * @param currency the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CREATED_BY
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CREATED_BY
     *
     * @param createdBy the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CREATION_DATE
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.CREATION_DATE
     *
     * @param creationDate the value for CIS_CROP_OTHER_SHAREHOLDER_IF.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATED_BY
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATE_DATE
     *
     * @return the value of CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_CROP_OTHER_SHAREHOLDER_IF.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}