package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisCourtDealInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.BELONGINGS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String belongings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.EXEC_COURT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String execCourt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.RECORD_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.RECORD_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String recordNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.INFO_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String infoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.DEAL_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Short dealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COURT_DEAL_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.SN_NO
     *
     * @return the value of CIS_COURT_DEAL_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.SN_NO
     *
     * @param snNo the value for CIS_COURT_DEAL_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.ID
     *
     * @return the value of CIS_COURT_DEAL_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.ID
     *
     * @param id the value for CIS_COURT_DEAL_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.APPLY_NO
     *
     * @return the value of CIS_COURT_DEAL_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_COURT_DEAL_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.CORP_NAME
     *
     * @return the value of CIS_COURT_DEAL_INFO.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.CORP_NAME
     *
     * @param corpName the value for CIS_COURT_DEAL_INFO.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.CURRENCY
     *
     * @return the value of CIS_COURT_DEAL_INFO.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.CURRENCY
     *
     * @param currency the value for CIS_COURT_DEAL_INFO.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.BELONGINGS
     *
     * @return the value of CIS_COURT_DEAL_INFO.BELONGINGS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getBelongings() {
        return belongings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.BELONGINGS
     *
     * @param belongings the value for CIS_COURT_DEAL_INFO.BELONGINGS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setBelongings(String belongings) {
        this.belongings = belongings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.EXEC_COURT
     *
     * @return the value of CIS_COURT_DEAL_INFO.EXEC_COURT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getExecCourt() {
        return execCourt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.EXEC_COURT
     *
     * @param execCourt the value for CIS_COURT_DEAL_INFO.EXEC_COURT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setExecCourt(String execCourt) {
        this.execCourt = execCourt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.STATUS
     *
     * @return the value of CIS_COURT_DEAL_INFO.STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.STATUS
     *
     * @param status the value for CIS_COURT_DEAL_INFO.STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.RECORD_TIME
     *
     * @return the value of CIS_COURT_DEAL_INFO.RECORD_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.RECORD_TIME
     *
     * @param recordTime the value for CIS_COURT_DEAL_INFO.RECORD_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.RECORD_NO
     *
     * @return the value of CIS_COURT_DEAL_INFO.RECORD_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.RECORD_NO
     *
     * @param recordNo the value for CIS_COURT_DEAL_INFO.RECORD_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.INFO_DATE
     *
     * @return the value of CIS_COURT_DEAL_INFO.INFO_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getInfoDate() {
        return infoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.INFO_DATE
     *
     * @param infoDate the value for CIS_COURT_DEAL_INFO.INFO_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setInfoDate(String infoDate) {
        this.infoDate = infoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.DEAL_TYPE
     *
     * @return the value of CIS_COURT_DEAL_INFO.DEAL_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Short getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.DEAL_TYPE
     *
     * @param dealType the value for CIS_COURT_DEAL_INFO.DEAL_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setDealType(Short dealType) {
        this.dealType = dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.CREATED_BY
     *
     * @return the value of CIS_COURT_DEAL_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_COURT_DEAL_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.CREATION_DATE
     *
     * @return the value of CIS_COURT_DEAL_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_COURT_DEAL_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_COURT_DEAL_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_COURT_DEAL_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COURT_DEAL_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_COURT_DEAL_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COURT_DEAL_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_COURT_DEAL_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}