package com.ctc.credit.kernel.model.pengyuan;

import java.math.BigDecimal;
import java.util.Date;

public class CisCollegeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.COLLEGE_OLD_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String collegeOldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.CREATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.CREATE_YEARS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private BigDecimal createYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.COLLEGE_VARCHAR2ACTER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String collegeVarchar2acter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.COLLEGE_LEVEL
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String collegeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.ACTER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String acter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.COLLEGE_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String collegeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.SCIENCE_BATCH
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String scienceBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.ART_BATCH
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String artBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_COLLEGE_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.SN_NO
     *
     * @return the value of CIS_COLLEGE_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.SN_NO
     *
     * @param snNo the value for CIS_COLLEGE_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.ID
     *
     * @return the value of CIS_COLLEGE_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.ID
     *
     * @param id the value for CIS_COLLEGE_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.APPLY_NO
     *
     * @return the value of CIS_COLLEGE_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_COLLEGE_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.COLLEGE
     *
     * @return the value of CIS_COLLEGE_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.COLLEGE
     *
     * @param college the value for CIS_COLLEGE_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.COLLEGE_OLD_NAME
     *
     * @return the value of CIS_COLLEGE_INFO.COLLEGE_OLD_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollegeOldName() {
        return collegeOldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.COLLEGE_OLD_NAME
     *
     * @param collegeOldName the value for CIS_COLLEGE_INFO.COLLEGE_OLD_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollegeOldName(String collegeOldName) {
        this.collegeOldName = collegeOldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.ADDRESS
     *
     * @return the value of CIS_COLLEGE_INFO.ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.ADDRESS
     *
     * @param address the value for CIS_COLLEGE_INFO.ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.CREATE_DATE
     *
     * @return the value of CIS_COLLEGE_INFO.CREATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.CREATE_DATE
     *
     * @param createDate the value for CIS_COLLEGE_INFO.CREATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.CREATE_YEARS
     *
     * @return the value of CIS_COLLEGE_INFO.CREATE_YEARS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public BigDecimal getCreateYears() {
        return createYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.CREATE_YEARS
     *
     * @param createYears the value for CIS_COLLEGE_INFO.CREATE_YEARS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreateYears(BigDecimal createYears) {
        this.createYears = createYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.COLLEGE_VARCHAR2ACTER
     *
     * @return the value of CIS_COLLEGE_INFO.COLLEGE_VARCHAR2ACTER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollegeVarchar2acter() {
        return collegeVarchar2acter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.COLLEGE_CHARACTER
     *
     * @param collegeVarchar2acter the value for CIS_COLLEGE_INFO.COLLEGE_CHARACTER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollegeVarchar2acter(String collegeVarchar2acter) {
        this.collegeVarchar2acter = collegeVarchar2acter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.COLLEGE_LEVEL
     *
     * @return the value of CIS_COLLEGE_INFO.COLLEGE_LEVEL
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollegeLevel() {
        return collegeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.COLLEGE_LEVEL
     *
     * @param collegeLevel the value for CIS_COLLEGE_INFO.COLLEGE_LEVEL
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollegeLevel(String collegeLevel) {
        this.collegeLevel = collegeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.CHARACTER
     *
     * @return the value of CIS_COLLEGE_INFO.CHARACTER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getActer() {
        return acter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.ACTER
     *
     * @param acter the value for CIS_COLLEGE_INFO.ACTER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setActer(String acter) {
        this.acter = acter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.COLLEGE_TYPE
     *
     * @return the value of CIS_COLLEGE_INFO.COLLEGE_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollegeType() {
        return collegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.COLLEGE_TYPE
     *
     * @param collegeType the value for CIS_COLLEGE_INFO.COLLEGE_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollegeType(String collegeType) {
        this.collegeType = collegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.SCIENCE_BATCH
     *
     * @return the value of CIS_COLLEGE_INFO.SCIENCE_BATCH
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getScienceBatch() {
        return scienceBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.SCIENCE_BATCH
     *
     * @param scienceBatch the value for CIS_COLLEGE_INFO.SCIENCE_BATCH
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setScienceBatch(String scienceBatch) {
        this.scienceBatch = scienceBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.ART_BATCH
     *
     * @return the value of CIS_COLLEGE_INFO.ART_BATCH
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getArtBatch() {
        return artBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.ART_BATCH
     *
     * @param artBatch the value for CIS_COLLEGE_INFO.ART_BATCH
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setArtBatch(String artBatch) {
        this.artBatch = artBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.CREATED_BY
     *
     * @return the value of CIS_COLLEGE_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_COLLEGE_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.CREATION_DATE
     *
     * @return the value of CIS_COLLEGE_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_COLLEGE_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_COLLEGE_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_COLLEGE_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_COLLEGE_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_COLLEGE_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_COLLEGE_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_COLLEGE_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}