package com.ctc.credit.kernel.model.pengyuan;

import java.math.BigDecimal;
import java.util.Date;

public class CisCropInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CROP_CODE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.REGISTER_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.ARTIFICIAL_PERSON
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String artificialPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.ARTIFICIAL_PERSON2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String artificialPerson2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.REGIST_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.HANDLE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String handleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CANCEL_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.URL
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CROP_STATUS2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatus2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CROP_STATUS2_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatus2Desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.FUND_CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String fundCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private BigDecimal registFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.REGIST_FUND2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private BigDecimal registFund2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.FUND_CURRENCY2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String fundCurrency2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CROP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.ECONOMIC_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String economicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.TRADE_CODE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String tradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.TRADE_NAME1
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String tradeName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.TRADE_NAME2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String tradeName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.TRADE_NAME3
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String tradeName3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.TRADE_NAME4
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String tradeName4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.STAFF_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.MANAGE_RANGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String manageRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.OPEN_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.MANAGE_BEGIN_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String manageBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.MANAGE_END_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String manageEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CORP_TYPE_ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CORP_TYPE_CAPTION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpTypeCaption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.ALLOW_MANAGE_PROJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String allowManageProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.GENERAL_MANAGE_PROJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String generalManageProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.MANAGE_RANGE_FASHION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String manageRangeFashion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.REGISTER_DEPARTMENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registerDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.LAST_CHECK_YEAR
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastCheckYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.LAST_CHECK_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.LOGOUT_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String logoutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.REVOKE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String revokeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_CROP_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.SN_NO
     *
     * @return the value of CIS_CROP_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.SN_NO
     *
     * @param snNo the value for CIS_CROP_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.ID
     *
     * @return the value of CIS_CROP_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.ID
     *
     * @param id the value for CIS_CROP_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.APPLY_NO
     *
     * @return the value of CIS_CROP_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_CROP_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CORP_NAME
     *
     * @return the value of CIS_CROP_INFO.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CORP_NAME
     *
     * @param corpName the value for CIS_CROP_INFO.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CROP_CODE
     *
     * @return the value of CIS_CROP_INFO.CROP_CODE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropCode() {
        return cropCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CROP_CODE
     *
     * @param cropCode the value for CIS_CROP_INFO.CROP_CODE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropCode(String cropCode) {
        this.cropCode = cropCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.REGISTER_NO
     *
     * @return the value of CIS_CROP_INFO.REGISTER_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegisterNo() {
        return registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.REGISTER_NO
     *
     * @param registerNo the value for CIS_CROP_INFO.REGISTER_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegisterNo(String registerNo) {
        this.registerNo = registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.ARTIFICIAL_PERSON
     *
     * @return the value of CIS_CROP_INFO.ARTIFICIAL_PERSON
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getArtificialPerson() {
        return artificialPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.ARTIFICIAL_PERSON
     *
     * @param artificialPerson the value for CIS_CROP_INFO.ARTIFICIAL_PERSON
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setArtificialPerson(String artificialPerson) {
        this.artificialPerson = artificialPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.ARTIFICIAL_PERSON2
     *
     * @return the value of CIS_CROP_INFO.ARTIFICIAL_PERSON2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getArtificialPerson2() {
        return artificialPerson2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.ARTIFICIAL_PERSON2
     *
     * @param artificialPerson2 the value for CIS_CROP_INFO.ARTIFICIAL_PERSON2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setArtificialPerson2(String artificialPerson2) {
        this.artificialPerson2 = artificialPerson2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.REGIST_DATE
     *
     * @return the value of CIS_CROP_INFO.REGIST_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.REGIST_DATE
     *
     * @param registDate the value for CIS_CROP_INFO.REGIST_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistDate(String registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.HANDLE_DATE
     *
     * @return the value of CIS_CROP_INFO.HANDLE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getHandleDate() {
        return handleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.HANDLE_DATE
     *
     * @param handleDate the value for CIS_CROP_INFO.HANDLE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setHandleDate(String handleDate) {
        this.handleDate = handleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CANCEL_DATE
     *
     * @return the value of CIS_CROP_INFO.CANCEL_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CANCEL_DATE
     *
     * @param cancelDate the value for CIS_CROP_INFO.CANCEL_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCancelDate(String cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.URL
     *
     * @return the value of CIS_CROP_INFO.URL
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.URL
     *
     * @param url the value for CIS_CROP_INFO.URL
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CROP_STATUS
     *
     * @return the value of CIS_CROP_INFO.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatus() {
        return cropStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CROP_STATUS
     *
     * @param cropStatus the value for CIS_CROP_INFO.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatus(String cropStatus) {
        this.cropStatus = cropStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CROP_STATUS_DESC
     *
     * @return the value of CIS_CROP_INFO.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatusDesc() {
        return cropStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CROP_STATUS_DESC
     *
     * @param cropStatusDesc the value for CIS_CROP_INFO.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatusDesc(String cropStatusDesc) {
        this.cropStatusDesc = cropStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CROP_STATUS2
     *
     * @return the value of CIS_CROP_INFO.CROP_STATUS2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatus2() {
        return cropStatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CROP_STATUS2
     *
     * @param cropStatus2 the value for CIS_CROP_INFO.CROP_STATUS2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatus2(String cropStatus2) {
        this.cropStatus2 = cropStatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CROP_STATUS2_DESC
     *
     * @return the value of CIS_CROP_INFO.CROP_STATUS2_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatus2Desc() {
        return cropStatus2Desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CROP_STATUS2_DESC
     *
     * @param cropStatus2Desc the value for CIS_CROP_INFO.CROP_STATUS2_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatus2Desc(String cropStatus2Desc) {
        this.cropStatus2Desc = cropStatus2Desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.FUND_CURRENCY
     *
     * @return the value of CIS_CROP_INFO.FUND_CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getFundCurrency() {
        return fundCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.FUND_CURRENCY
     *
     * @param fundCurrency the value for CIS_CROP_INFO.FUND_CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setFundCurrency(String fundCurrency) {
        this.fundCurrency = fundCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.REGIST_FUND
     *
     * @return the value of CIS_CROP_INFO.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public BigDecimal getRegistFund() {
        return registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.REGIST_FUND
     *
     * @param registFund the value for CIS_CROP_INFO.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistFund(BigDecimal registFund) {
        this.registFund = registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.REGIST_FUND2
     *
     * @return the value of CIS_CROP_INFO.REGIST_FUND2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public BigDecimal getRegistFund2() {
        return registFund2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.REGIST_FUND2
     *
     * @param registFund2 the value for CIS_CROP_INFO.REGIST_FUND2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistFund2(BigDecimal registFund2) {
        this.registFund2 = registFund2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.FUND_CURRENCY2
     *
     * @return the value of CIS_CROP_INFO.FUND_CURRENCY2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getFundCurrency2() {
        return fundCurrency2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.FUND_CURRENCY2
     *
     * @param fundCurrency2 the value for CIS_CROP_INFO.FUND_CURRENCY2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setFundCurrency2(String fundCurrency2) {
        this.fundCurrency2 = fundCurrency2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CROP_TYPE
     *
     * @return the value of CIS_CROP_INFO.CROP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropType() {
        return cropType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CROP_TYPE
     *
     * @param cropType the value for CIS_CROP_INFO.CROP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropType(String cropType) {
        this.cropType = cropType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.ECONOMIC_TYPE
     *
     * @return the value of CIS_CROP_INFO.ECONOMIC_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getEconomicType() {
        return economicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.ECONOMIC_TYPE
     *
     * @param economicType the value for CIS_CROP_INFO.ECONOMIC_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setEconomicType(String economicType) {
        this.economicType = economicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.TRADE_CODE
     *
     * @return the value of CIS_CROP_INFO.TRADE_CODE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getTradeCode() {
        return tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.TRADE_CODE
     *
     * @param tradeCode the value for CIS_CROP_INFO.TRADE_CODE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.TRADE_NAME1
     *
     * @return the value of CIS_CROP_INFO.TRADE_NAME1
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getTradeName1() {
        return tradeName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.TRADE_NAME1
     *
     * @param tradeName1 the value for CIS_CROP_INFO.TRADE_NAME1
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setTradeName1(String tradeName1) {
        this.tradeName1 = tradeName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.TRADE_NAME2
     *
     * @return the value of CIS_CROP_INFO.TRADE_NAME2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getTradeName2() {
        return tradeName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.TRADE_NAME2
     *
     * @param tradeName2 the value for CIS_CROP_INFO.TRADE_NAME2
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setTradeName2(String tradeName2) {
        this.tradeName2 = tradeName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.TRADE_NAME3
     *
     * @return the value of CIS_CROP_INFO.TRADE_NAME3
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getTradeName3() {
        return tradeName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.TRADE_NAME3
     *
     * @param tradeName3 the value for CIS_CROP_INFO.TRADE_NAME3
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setTradeName3(String tradeName3) {
        this.tradeName3 = tradeName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.TRADE_NAME4
     *
     * @return the value of CIS_CROP_INFO.TRADE_NAME4
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getTradeName4() {
        return tradeName4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.TRADE_NAME4
     *
     * @param tradeName4 the value for CIS_CROP_INFO.TRADE_NAME4
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setTradeName4(String tradeName4) {
        this.tradeName4 = tradeName4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.STAFF_NUMBER
     *
     * @return the value of CIS_CROP_INFO.STAFF_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.STAFF_NUMBER
     *
     * @param staffNumber the value for CIS_CROP_INFO.STAFF_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.MANAGE_RANGE
     *
     * @return the value of CIS_CROP_INFO.MANAGE_RANGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getManageRange() {
        return manageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.MANAGE_RANGE
     *
     * @param manageRange the value for CIS_CROP_INFO.MANAGE_RANGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setManageRange(String manageRange) {
        this.manageRange = manageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.OPEN_DATE
     *
     * @return the value of CIS_CROP_INFO.OPEN_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.OPEN_DATE
     *
     * @param openDate the value for CIS_CROP_INFO.OPEN_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.MANAGE_BEGIN_DATE
     *
     * @return the value of CIS_CROP_INFO.MANAGE_BEGIN_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getManageBeginDate() {
        return manageBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.MANAGE_BEGIN_DATE
     *
     * @param manageBeginDate the value for CIS_CROP_INFO.MANAGE_BEGIN_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setManageBeginDate(String manageBeginDate) {
        this.manageBeginDate = manageBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.MANAGE_END_DATE
     *
     * @return the value of CIS_CROP_INFO.MANAGE_END_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getManageEndDate() {
        return manageEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.MANAGE_END_DATE
     *
     * @param manageEndDate the value for CIS_CROP_INFO.MANAGE_END_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setManageEndDate(String manageEndDate) {
        this.manageEndDate = manageEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CORP_TYPE_ID
     *
     * @return the value of CIS_CROP_INFO.CORP_TYPE_ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpTypeId() {
        return corpTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CORP_TYPE_ID
     *
     * @param corpTypeId the value for CIS_CROP_INFO.CORP_TYPE_ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpTypeId(String corpTypeId) {
        this.corpTypeId = corpTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CORP_TYPE_CAPTION
     *
     * @return the value of CIS_CROP_INFO.CORP_TYPE_CAPTION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpTypeCaption() {
        return corpTypeCaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CORP_TYPE_CAPTION
     *
     * @param corpTypeCaption the value for CIS_CROP_INFO.CORP_TYPE_CAPTION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpTypeCaption(String corpTypeCaption) {
        this.corpTypeCaption = corpTypeCaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.ALLOW_MANAGE_PROJECT
     *
     * @return the value of CIS_CROP_INFO.ALLOW_MANAGE_PROJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getAllowManageProject() {
        return allowManageProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.ALLOW_MANAGE_PROJECT
     *
     * @param allowManageProject the value for CIS_CROP_INFO.ALLOW_MANAGE_PROJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setAllowManageProject(String allowManageProject) {
        this.allowManageProject = allowManageProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.GENERAL_MANAGE_PROJECT
     *
     * @return the value of CIS_CROP_INFO.GENERAL_MANAGE_PROJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getGeneralManageProject() {
        return generalManageProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.GENERAL_MANAGE_PROJECT
     *
     * @param generalManageProject the value for CIS_CROP_INFO.GENERAL_MANAGE_PROJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setGeneralManageProject(String generalManageProject) {
        this.generalManageProject = generalManageProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.MANAGE_RANGE_FASHION
     *
     * @return the value of CIS_CROP_INFO.MANAGE_RANGE_FASHION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getManageRangeFashion() {
        return manageRangeFashion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.MANAGE_RANGE_FASHION
     *
     * @param manageRangeFashion the value for CIS_CROP_INFO.MANAGE_RANGE_FASHION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setManageRangeFashion(String manageRangeFashion) {
        this.manageRangeFashion = manageRangeFashion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.REGISTER_DEPARTMENT
     *
     * @return the value of CIS_CROP_INFO.REGISTER_DEPARTMENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegisterDepartment() {
        return registerDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.REGISTER_DEPARTMENT
     *
     * @param registerDepartment the value for CIS_CROP_INFO.REGISTER_DEPARTMENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegisterDepartment(String registerDepartment) {
        this.registerDepartment = registerDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.LAST_CHECK_YEAR
     *
     * @return the value of CIS_CROP_INFO.LAST_CHECK_YEAR
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastCheckYear() {
        return lastCheckYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.LAST_CHECK_YEAR
     *
     * @param lastCheckYear the value for CIS_CROP_INFO.LAST_CHECK_YEAR
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastCheckYear(String lastCheckYear) {
        this.lastCheckYear = lastCheckYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.LAST_CHECK_DATE
     *
     * @return the value of CIS_CROP_INFO.LAST_CHECK_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastCheckDate() {
        return lastCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.LAST_CHECK_DATE
     *
     * @param lastCheckDate the value for CIS_CROP_INFO.LAST_CHECK_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastCheckDate(String lastCheckDate) {
        this.lastCheckDate = lastCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.LOGOUT_DATE
     *
     * @return the value of CIS_CROP_INFO.LOGOUT_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLogoutDate() {
        return logoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.LOGOUT_DATE
     *
     * @param logoutDate the value for CIS_CROP_INFO.LOGOUT_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLogoutDate(String logoutDate) {
        this.logoutDate = logoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.REVOKE_DATE
     *
     * @return the value of CIS_CROP_INFO.REVOKE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRevokeDate() {
        return revokeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.REVOKE_DATE
     *
     * @param revokeDate the value for CIS_CROP_INFO.REVOKE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRevokeDate(String revokeDate) {
        this.revokeDate = revokeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CREATED_BY
     *
     * @return the value of CIS_CROP_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_CROP_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.CREATION_DATE
     *
     * @return the value of CIS_CROP_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_CROP_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_CROP_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_CROP_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_CROP_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_CROP_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_CROP_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_CROP_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}