package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisDegreeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.LEVEL_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String levelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.START_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.GRADUATE_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String graduateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.STUDY_STYLE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String studyStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.STUDY_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String studyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.SPECIALTY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.SUBJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.DEGREE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.STUDY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String studyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.PHOTO_STYLE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String photoStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_DEGREE_INFO.PHOTO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.SN_NO
     *
     * @return the value of CIS_DEGREE_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.SN_NO
     *
     * @param snNo the value for CIS_DEGREE_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.ID
     *
     * @return the value of CIS_DEGREE_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.ID
     *
     * @param id the value for CIS_DEGREE_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.APPLY_NO
     *
     * @return the value of CIS_DEGREE_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_DEGREE_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.COLLEGE
     *
     * @return the value of CIS_DEGREE_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.COLLEGE
     *
     * @param college the value for CIS_DEGREE_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.LEVEL_NO
     *
     * @return the value of CIS_DEGREE_INFO.LEVEL_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLevelNo() {
        return levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.LEVEL_NO
     *
     * @param levelNo the value for CIS_DEGREE_INFO.LEVEL_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLevelNo(String levelNo) {
        this.levelNo = levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.START_TIME
     *
     * @return the value of CIS_DEGREE_INFO.START_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.START_TIME
     *
     * @param startTime the value for CIS_DEGREE_INFO.START_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.GRADUATE_TIME
     *
     * @return the value of CIS_DEGREE_INFO.GRADUATE_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getGraduateTime() {
        return graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.GRADUATE_TIME
     *
     * @param graduateTime the value for CIS_DEGREE_INFO.GRADUATE_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setGraduateTime(String graduateTime) {
        this.graduateTime = graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.STUDY_STYLE
     *
     * @return the value of CIS_DEGREE_INFO.STUDY_STYLE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStudyStyle() {
        return studyStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.STUDY_STYLE
     *
     * @param studyStyle the value for CIS_DEGREE_INFO.STUDY_STYLE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStudyStyle(String studyStyle) {
        this.studyStyle = studyStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.STUDY_TYPE
     *
     * @return the value of CIS_DEGREE_INFO.STUDY_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStudyType() {
        return studyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.STUDY_TYPE
     *
     * @param studyType the value for CIS_DEGREE_INFO.STUDY_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStudyType(String studyType) {
        this.studyType = studyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.SPECIALTY
     *
     * @return the value of CIS_DEGREE_INFO.SPECIALTY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.SPECIALTY
     *
     * @param specialty the value for CIS_DEGREE_INFO.SPECIALTY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.SUBJECT
     *
     * @return the value of CIS_DEGREE_INFO.SUBJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.SUBJECT
     *
     * @param subject the value for CIS_DEGREE_INFO.SUBJECT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.DEGREE
     *
     * @return the value of CIS_DEGREE_INFO.DEGREE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.DEGREE
     *
     * @param degree the value for CIS_DEGREE_INFO.DEGREE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.STUDY_RESULT
     *
     * @return the value of CIS_DEGREE_INFO.STUDY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStudyResult() {
        return studyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.STUDY_RESULT
     *
     * @param studyResult the value for CIS_DEGREE_INFO.STUDY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStudyResult(String studyResult) {
        this.studyResult = studyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.PHOTO_STYLE
     *
     * @return the value of CIS_DEGREE_INFO.PHOTO_STYLE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getPhotoStyle() {
        return photoStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.PHOTO_STYLE
     *
     * @param photoStyle the value for CIS_DEGREE_INFO.PHOTO_STYLE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setPhotoStyle(String photoStyle) {
        this.photoStyle = photoStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.CREATED_BY
     *
     * @return the value of CIS_DEGREE_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_DEGREE_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.CREATION_DATE
     *
     * @return the value of CIS_DEGREE_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_DEGREE_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_DEGREE_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_DEGREE_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_DEGREE_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_DEGREE_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_DEGREE_INFO.PHOTO
     *
     * @return the value of CIS_DEGREE_INFO.PHOTO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_DEGREE_INFO.PHOTO
     *
     * @param photo the value for CIS_DEGREE_INFO.PHOTO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}