package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisEducationCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.CHECK_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Short checkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_CHECK.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.SN_NO
     *
     * @return the value of CIS_EDUCATION_CHECK.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.SN_NO
     *
     * @param snNo the value for CIS_EDUCATION_CHECK.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.ID
     *
     * @return the value of CIS_EDUCATION_CHECK.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.ID
     *
     * @param id the value for CIS_EDUCATION_CHECK.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.APPLY_NO
     *
     * @return the value of CIS_EDUCATION_CHECK.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.APPLY_NO
     *
     * @param applyNo the value for CIS_EDUCATION_CHECK.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.RESULT
     *
     * @return the value of CIS_EDUCATION_CHECK.RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.RESULT
     *
     * @param result the value for CIS_EDUCATION_CHECK.RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.CHECK_TYPE
     *
     * @return the value of CIS_EDUCATION_CHECK.CHECK_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Short getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.CHECK_TYPE
     *
     * @param checkType the value for CIS_EDUCATION_CHECK.CHECK_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCheckType(Short checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.CREATED_BY
     *
     * @return the value of CIS_EDUCATION_CHECK.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.CREATED_BY
     *
     * @param createdBy the value for CIS_EDUCATION_CHECK.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.CREATION_DATE
     *
     * @return the value of CIS_EDUCATION_CHECK.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.CREATION_DATE
     *
     * @param creationDate the value for CIS_EDUCATION_CHECK.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.LAST_UPDATED_BY
     *
     * @return the value of CIS_EDUCATION_CHECK.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_EDUCATION_CHECK.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_CHECK.LAST_UPDATE_DATE
     *
     * @return the value of CIS_EDUCATION_CHECK.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_CHECK.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_EDUCATION_CHECK.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}