package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisEducationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.STANDARD_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String standardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.DEGREE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.SPECIALTY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String college;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.GRADUATE_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String graduateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.GRADUATE_YEARS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String graduateYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.AGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String originalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.VERIFY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String verifyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.EDUCATION_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Short educationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_EDUCATION_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.SN_NO
     *
     * @return the value of CIS_EDUCATION_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.SN_NO
     *
     * @param snNo the value for CIS_EDUCATION_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.ID
     *
     * @return the value of CIS_EDUCATION_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.ID
     *
     * @param id the value for CIS_EDUCATION_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.APPLY_NO
     *
     * @return the value of CIS_EDUCATION_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_EDUCATION_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.STANDARD_NAME
     *
     * @return the value of CIS_EDUCATION_INFO.STANDARD_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getStandardName() {
        return standardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.STANDARD_NAME
     *
     * @param standardName the value for CIS_EDUCATION_INFO.STANDARD_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setStandardName(String standardName) {
        this.standardName = standardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.ID_NUMBER
     *
     * @return the value of CIS_EDUCATION_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.ID_NUMBER
     *
     * @param idNumber the value for CIS_EDUCATION_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.DEGREE
     *
     * @return the value of CIS_EDUCATION_INFO.DEGREE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.DEGREE
     *
     * @param degree the value for CIS_EDUCATION_INFO.DEGREE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.SPECIALTY
     *
     * @return the value of CIS_EDUCATION_INFO.SPECIALTY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.SPECIALTY
     *
     * @param specialty the value for CIS_EDUCATION_INFO.SPECIALTY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.COLLEGE
     *
     * @return the value of CIS_EDUCATION_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.COLLEGE
     *
     * @param college the value for CIS_EDUCATION_INFO.COLLEGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.GRADUATE_TIME
     *
     * @return the value of CIS_EDUCATION_INFO.GRADUATE_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getGraduateTime() {
        return graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.GRADUATE_TIME
     *
     * @param graduateTime the value for CIS_EDUCATION_INFO.GRADUATE_TIME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setGraduateTime(String graduateTime) {
        this.graduateTime = graduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.GRADUATE_YEARS
     *
     * @return the value of CIS_EDUCATION_INFO.GRADUATE_YEARS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getGraduateYears() {
        return graduateYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.GRADUATE_YEARS
     *
     * @param graduateYears the value for CIS_EDUCATION_INFO.GRADUATE_YEARS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setGraduateYears(String graduateYears) {
        this.graduateYears = graduateYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.BIRTH_DAY
     *
     * @return the value of CIS_EDUCATION_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.BIRTH_DAY
     *
     * @param birthDay the value for CIS_EDUCATION_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.SEX
     *
     * @return the value of CIS_EDUCATION_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.SEX
     *
     * @param sex the value for CIS_EDUCATION_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.AGE
     *
     * @return the value of CIS_EDUCATION_INFO.AGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.AGE
     *
     * @param age the value for CIS_EDUCATION_INFO.AGE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.ORIGINAL_ADDRESS
     *
     * @return the value of CIS_EDUCATION_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getOriginalAddress() {
        return originalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.ORIGINAL_ADDRESS
     *
     * @param originalAddress the value for CIS_EDUCATION_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setOriginalAddress(String originalAddress) {
        this.originalAddress = originalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.VERIFY_RESULT
     *
     * @return the value of CIS_EDUCATION_INFO.VERIFY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getVerifyResult() {
        return verifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.VERIFY_RESULT
     *
     * @param verifyResult the value for CIS_EDUCATION_INFO.VERIFY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setVerifyResult(String verifyResult) {
        this.verifyResult = verifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.EDUCATION_TYPE
     *
     * @return the value of CIS_EDUCATION_INFO.EDUCATION_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Short getEducationType() {
        return educationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.EDUCATION_TYPE
     *
     * @param educationType the value for CIS_EDUCATION_INFO.EDUCATION_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setEducationType(Short educationType) {
        this.educationType = educationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.CREATED_BY
     *
     * @return the value of CIS_EDUCATION_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_EDUCATION_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.CREATION_DATE
     *
     * @return the value of CIS_EDUCATION_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_EDUCATION_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_EDUCATION_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_EDUCATION_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_EDUCATION_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_EDUCATION_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_EDUCATION_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_EDUCATION_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}