package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisMoblieCheckInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.RESULTTYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String resulttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.CONTACT_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.AREA_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String areaDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.MOBILE_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String mobileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.CHECK_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Short checkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_MOBLIE_CHECK_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.SN_NO
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.SN_NO
     *
     * @param snNo the value for CIS_MOBLIE_CHECK_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.ID
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.ID
     *
     * @param id the value for CIS_MOBLIE_CHECK_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.APPLY_NO
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_MOBLIE_CHECK_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.RESULTTYPE
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.RESULTTYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getResulttype() {
        return resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.RESULTTYPE
     *
     * @param resulttype the value for CIS_MOBLIE_CHECK_INFO.RESULTTYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setResulttype(String resulttype) {
        this.resulttype = resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.CONTACT_NAME
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.CONTACT_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.CONTACT_NAME
     *
     * @param contactName the value for CIS_MOBLIE_CHECK_INFO.CONTACT_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.AREA_DESC
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.AREA_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getAreaDesc() {
        return areaDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.AREA_DESC
     *
     * @param areaDesc the value for CIS_MOBLIE_CHECK_INFO.AREA_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setAreaDesc(String areaDesc) {
        this.areaDesc = areaDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.MOBILE_TYPE
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.MOBILE_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getMobileType() {
        return mobileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.MOBILE_TYPE
     *
     * @param mobileType the value for CIS_MOBLIE_CHECK_INFO.MOBILE_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setMobileType(String mobileType) {
        this.mobileType = mobileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.ADDRESS
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.ADDRESS
     *
     * @param address the value for CIS_MOBLIE_CHECK_INFO.ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.CHECK_TYPE
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.CHECK_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Short getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.CHECK_TYPE
     *
     * @param checkType the value for CIS_MOBLIE_CHECK_INFO.CHECK_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCheckType(Short checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.CREATED_BY
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_MOBLIE_CHECK_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.CREATION_DATE
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_MOBLIE_CHECK_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_MOBLIE_CHECK_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_MOBLIE_CHECK_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_MOBLIE_CHECK_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_MOBLIE_CHECK_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_MOBLIE_CHECK_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}