package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisOrgShareholderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.SHAREHOLDER_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String shareholderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributiveFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributivePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.SN_NO
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.SN_NO
     *
     * @param snNo the value for CIS_ORG_SHAREHOLDER_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.ID
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.ID
     *
     * @param id the value for CIS_ORG_SHAREHOLDER_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.APPLY_NO
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_ORG_SHAREHOLDER_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.SHAREHOLDER_NAME
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.SHAREHOLDER_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getShareholderName() {
        return shareholderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.SHAREHOLDER_NAME
     *
     * @param shareholderName the value for CIS_ORG_SHAREHOLDER_INFO.SHAREHOLDER_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setShareholderName(String shareholderName) {
        this.shareholderName = shareholderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_FUND
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributiveFund() {
        return contributiveFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_FUND
     *
     * @param contributiveFund the value for CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributiveFund(String contributiveFund) {
        this.contributiveFund = contributiveFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_PERCENT
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributivePercent() {
        return contributivePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_PERCENT
     *
     * @param contributivePercent the value for CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributivePercent(String contributivePercent) {
        this.contributivePercent = contributivePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.CURRENCY
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.CURRENCY
     *
     * @param currency the value for CIS_ORG_SHAREHOLDER_INFO.CURRENCY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_DATE
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributiveDate() {
        return contributiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_DATE
     *
     * @param contributiveDate the value for CIS_ORG_SHAREHOLDER_INFO.CONTRIBUTIVE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributiveDate(String contributiveDate) {
        this.contributiveDate = contributiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.CREATED_BY
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_ORG_SHAREHOLDER_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.CREATION_DATE
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_ORG_SHAREHOLDER_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_ORG_SHAREHOLDER_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}