package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisOstaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.CERTIFICATE_ID
     * 证书编号
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String certificateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.OCCUPATION
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.LEVELS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.PUBLISH_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.PUBLISH_ORG
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String publicOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.CITY_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.AVG_SALARY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String avgSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.AVG_SALARY_PROVINCE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String avgSalaryProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.AVG_SALARY_CITY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String avgSalaryCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.INFO_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String infoDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_OSTA_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.SN_NO
     *
     * @return the value of CIS_OSTA_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.SN_NO
     *
     * @param snNo the value for CIS_OSTA_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.ID
     *
     * @return the value of CIS_OSTA_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.ID
     *
     * @param id the value for CIS_OSTA_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.APPLY_NO
     *
     * @return the value of CIS_OSTA_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_OSTA_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    public String getCertificateId() {
		return certificateId;
	}

	public void setCertificateId(String certificateId) {
		this.certificateId = certificateId;
	}

	public String getOccupation() {
		return occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getLevels() {
		return levels;
	}

	public void setLevels(String levels) {
		this.levels = levels;
	}

	public String getPublishDate() {
		return publishDate;
	}

	public void setPublishDate(String publishDate) {
		this.publishDate = publishDate;
	}

	public String getPublicOrg() {
		return publicOrg;
	}

	public void setPublicOrg(String publicOrg) {
		this.publicOrg = publicOrg;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getAvgSalary() {
		return avgSalary;
	}

	public void setAvgSalary(String avgSalary) {
		this.avgSalary = avgSalary;
	}

	public String getAvgSalaryProvince() {
		return avgSalaryProvince;
	}

	public void setAvgSalaryProvince(String avgSalaryProvince) {
		this.avgSalaryProvince = avgSalaryProvince;
	}

	public String getAvgSalaryCity() {
		return avgSalaryCity;
	}

	public void setAvgSalaryCity(String avgSalaryCity) {
		this.avgSalaryCity = avgSalaryCity;
	}

	public String getInfoDate() {
		return infoDate;
	}

	public void setInfoDate(String infoDate) {
		this.infoDate = infoDate;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.CREATED_BY
     *
     * @return the value of CIS_OSTA_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_OSTA_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.CREATION_DATE
     *
     * @return the value of CIS_OSTA_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_OSTA_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_OSTA_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_OSTA_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_OSTA_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_OSTA_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_OSTA_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_OSTA_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}