package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisPersonShareStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.INVESTOR_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String investorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.REGISTER_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CORP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CORP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CORP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CORP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpStatusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributiveFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String contributivePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_SHARE_STOCK.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.SN_NO
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.SN_NO
     *
     * @param snNo the value for CIS_PERSON_SHARE_STOCK.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.ID
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.ID
     *
     * @param id the value for CIS_PERSON_SHARE_STOCK.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.APPLY_NO
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.APPLY_NO
     *
     * @param applyNo the value for CIS_PERSON_SHARE_STOCK.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.INVESTOR_NAME
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.INVESTOR_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getInvestorName() {
        return investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.INVESTOR_NAME
     *
     * @param investorName the value for CIS_PERSON_SHARE_STOCK.INVESTOR_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setInvestorName(String investorName) {
        this.investorName = investorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CORP_NAME
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CORP_NAME
     *
     * @param corpName the value for CIS_PERSON_SHARE_STOCK.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.REGISTER_NO
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.REGISTER_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegisterNo() {
        return registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.REGISTER_NO
     *
     * @param registerNo the value for CIS_PERSON_SHARE_STOCK.REGISTER_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegisterNo(String registerNo) {
        this.registerNo = registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CORP_TYPE
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CORP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpType() {
        return corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CORP_TYPE
     *
     * @param corpType the value for CIS_PERSON_SHARE_STOCK.CORP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpType(String corpType) {
        this.corpType = corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CORP_TYPE_DESC
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CORP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpTypeDesc() {
        return corpTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CORP_TYPE_DESC
     *
     * @param corpTypeDesc the value for CIS_PERSON_SHARE_STOCK.CORP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpTypeDesc(String corpTypeDesc) {
        this.corpTypeDesc = corpTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.REGIST_FUND
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegistFund() {
        return registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.REGIST_FUND
     *
     * @param registFund the value for CIS_PERSON_SHARE_STOCK.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistFund(String registFund) {
        this.registFund = registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CORP_STATUS
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CORP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpStatus() {
        return corpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CORP_STATUS
     *
     * @param corpStatus the value for CIS_PERSON_SHARE_STOCK.CORP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpStatus(String corpStatus) {
        this.corpStatus = corpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CORP_STATUS_DESC
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CORP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpStatusDesc() {
        return corpStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CORP_STATUS_DESC
     *
     * @param corpStatusDesc the value for CIS_PERSON_SHARE_STOCK.CORP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpStatusDesc(String corpStatusDesc) {
        this.corpStatusDesc = corpStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_FUND
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributiveFund() {
        return contributiveFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_FUND
     *
     * @param contributiveFund the value for CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributiveFund(String contributiveFund) {
        this.contributiveFund = contributiveFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_PERCENT
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getContributivePercent() {
        return contributivePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_PERCENT
     *
     * @param contributivePercent the value for CIS_PERSON_SHARE_STOCK.CONTRIBUTIVE_PERCENT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setContributivePercent(String contributivePercent) {
        this.contributivePercent = contributivePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CREATED_BY
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CREATED_BY
     *
     * @param createdBy the value for CIS_PERSON_SHARE_STOCK.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.CREATION_DATE
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.CREATION_DATE
     *
     * @param creationDate the value for CIS_PERSON_SHARE_STOCK.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.LAST_UPDATED_BY
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_PERSON_SHARE_STOCK.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_SHARE_STOCK.LAST_UPDATE_DATE
     *
     * @return the value of CIS_PERSON_SHARE_STOCK.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_SHARE_STOCK.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_PERSON_SHARE_STOCK.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}