package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisPersonIdInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String originalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.VERIFY_PARITY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String verifyParity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.VERIFY_AREA
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String verifyArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.VERIFY_BIRTHDAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String verifyBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.ID_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.VERIFY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String verifyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_ID_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.SN_NO
     *
     * @return the value of CIS_PERSON_ID_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.SN_NO
     *
     * @param snNo the value for CIS_PERSON_ID_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.ID
     *
     * @return the value of CIS_PERSON_ID_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.ID
     *
     * @param id the value for CIS_PERSON_ID_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.APPLY_NO
     *
     * @return the value of CIS_PERSON_ID_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_PERSON_ID_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.ID_NUMBER
     *
     * @return the value of CIS_PERSON_ID_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.ID_NUMBER
     *
     * @param idNumber the value for CIS_PERSON_ID_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.BIRTH_DAY
     *
     * @return the value of CIS_PERSON_ID_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.BIRTH_DAY
     *
     * @param birthDay the value for CIS_PERSON_ID_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.SEX
     *
     * @return the value of CIS_PERSON_ID_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.SEX
     *
     * @param sex the value for CIS_PERSON_ID_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.ORIGINAL_ADDRESS
     *
     * @return the value of CIS_PERSON_ID_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getOriginalAddress() {
        return originalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.ORIGINAL_ADDRESS
     *
     * @param originalAddress the value for CIS_PERSON_ID_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setOriginalAddress(String originalAddress) {
        this.originalAddress = originalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.VERIFY_PARITY
     *
     * @return the value of CIS_PERSON_ID_INFO.VERIFY_PARITY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getVerifyParity() {
        return verifyParity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.VERIFY_PARITY
     *
     * @param verifyParity the value for CIS_PERSON_ID_INFO.VERIFY_PARITY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setVerifyParity(String verifyParity) {
        this.verifyParity = verifyParity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.VERIFY_AREA
     *
     * @return the value of CIS_PERSON_ID_INFO.VERIFY_AREA
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getVerifyArea() {
        return verifyArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.VERIFY_AREA
     *
     * @param verifyArea the value for CIS_PERSON_ID_INFO.VERIFY_AREA
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setVerifyArea(String verifyArea) {
        this.verifyArea = verifyArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.VERIFY_BIRTHDAY
     *
     * @return the value of CIS_PERSON_ID_INFO.VERIFY_BIRTHDAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getVerifyBirthday() {
        return verifyBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.VERIFY_BIRTHDAY
     *
     * @param verifyBirthday the value for CIS_PERSON_ID_INFO.VERIFY_BIRTHDAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setVerifyBirthday(String verifyBirthday) {
        this.verifyBirthday = verifyBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.ID_TYPE
     *
     * @return the value of CIS_PERSON_ID_INFO.ID_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.ID_TYPE
     *
     * @param idType the value for CIS_PERSON_ID_INFO.ID_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setIdType(String idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.VERIFY_RESULT
     *
     * @return the value of CIS_PERSON_ID_INFO.VERIFY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getVerifyResult() {
        return verifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.VERIFY_RESULT
     *
     * @param verifyResult the value for CIS_PERSON_ID_INFO.VERIFY_RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setVerifyResult(String verifyResult) {
        this.verifyResult = verifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.CREATED_BY
     *
     * @return the value of CIS_PERSON_ID_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_PERSON_ID_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.CREATION_DATE
     *
     * @return the value of CIS_PERSON_ID_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_PERSON_ID_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_PERSON_ID_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_PERSON_ID_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_ID_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_PERSON_ID_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_ID_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_PERSON_ID_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}