package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisPersonIndentityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.TARGET_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String targetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.HISTORY_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String historyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.REGISTER_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String originalAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_PERSON_INDENTITY_INFO.PHOTO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.SN_NO
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.SN_NO
     *
     * @param snNo the value for CIS_PERSON_INDENTITY_INFO.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.ID
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.ID
     *
     * @param id the value for CIS_PERSON_INDENTITY_INFO.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.APPLY_NO
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.APPLY_NO
     *
     * @param applyNo the value for CIS_PERSON_INDENTITY_INFO.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.TARGET_NAME
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.TARGET_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.TARGET_NAME
     *
     * @param targetName the value for CIS_PERSON_INDENTITY_INFO.TARGET_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.ID_NUMBER
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.ID_NUMBER
     *
     * @param idNumber the value for CIS_PERSON_INDENTITY_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.SEX
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.SEX
     *
     * @param sex the value for CIS_PERSON_INDENTITY_INFO.SEX
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.BIRTH_DAY
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.BIRTH_DAY
     *
     * @param birthDay the value for CIS_PERSON_INDENTITY_INFO.BIRTH_DAY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.HISTORY_NAME
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.HISTORY_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getHistoryName() {
        return historyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.HISTORY_NAME
     *
     * @param historyName the value for CIS_PERSON_INDENTITY_INFO.HISTORY_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setHistoryName(String historyName) {
        this.historyName = historyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.REGISTER_ADDRESS
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.REGISTER_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegisterAddress() {
        return registerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.REGISTER_ADDRESS
     *
     * @param registerAddress the value for CIS_PERSON_INDENTITY_INFO.REGISTER_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegisterAddress(String registerAddress) {
        this.registerAddress = registerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.ORIGINAL_ADDRESS
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getOriginalAddress() {
        return originalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.ORIGINAL_ADDRESS
     *
     * @param originalAddress the value for CIS_PERSON_INDENTITY_INFO.ORIGINAL_ADDRESS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setOriginalAddress(String originalAddress) {
        this.originalAddress = originalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.RESULT
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.RESULT
     *
     * @param result the value for CIS_PERSON_INDENTITY_INFO.RESULT
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.CREATED_BY
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.CREATED_BY
     *
     * @param createdBy the value for CIS_PERSON_INDENTITY_INFO.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.CREATION_DATE
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.CREATION_DATE
     *
     * @param creationDate the value for CIS_PERSON_INDENTITY_INFO.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.LAST_UPDATED_BY
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_PERSON_INDENTITY_INFO.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.LAST_UPDATE_DATE
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_PERSON_INDENTITY_INFO.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_PERSON_INDENTITY_INFO.PHOTO
     *
     * @return the value of CIS_PERSON_INDENTITY_INFO.PHOTO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_PERSON_INDENTITY_INFO.PHOTO
     *
     * @param photo the value for CIS_PERSON_INDENTITY_INFO.PHOTO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}