package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CisSeniorManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String snNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.JOB_HOLDER_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String jobHolderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.REGIST_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CORP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CORP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String corpTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String registFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String cropStatusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.POSITION_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String positionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.POSITION_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String positionTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private String lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CIS_SENIOR_MANAGER.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.SN_NO
     *
     * @return the value of CIS_SENIOR_MANAGER.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getSnNo() {
        return snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.SN_NO
     *
     * @param snNo the value for CIS_SENIOR_MANAGER.SN_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setSnNo(String snNo) {
        this.snNo = snNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.ID
     *
     * @return the value of CIS_SENIOR_MANAGER.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.ID
     *
     * @param id the value for CIS_SENIOR_MANAGER.ID
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.APPLY_NO
     *
     * @return the value of CIS_SENIOR_MANAGER.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.APPLY_NO
     *
     * @param applyNo the value for CIS_SENIOR_MANAGER.APPLY_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.JOB_HOLDER_NAME
     *
     * @return the value of CIS_SENIOR_MANAGER.JOB_HOLDER_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getJobHolderName() {
        return jobHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.JOB_HOLDER_NAME
     *
     * @param jobHolderName the value for CIS_SENIOR_MANAGER.JOB_HOLDER_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setJobHolderName(String jobHolderName) {
        this.jobHolderName = jobHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CORP_NAME
     *
     * @return the value of CIS_SENIOR_MANAGER.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CORP_NAME
     *
     * @param corpName the value for CIS_SENIOR_MANAGER.CORP_NAME
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.REGIST_NO
     *
     * @return the value of CIS_SENIOR_MANAGER.REGIST_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegistNo() {
        return registNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.REGIST_NO
     *
     * @param registNo the value for CIS_SENIOR_MANAGER.REGIST_NO
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistNo(String registNo) {
        this.registNo = registNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CORP_TYPE
     *
     * @return the value of CIS_SENIOR_MANAGER.CORP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpType() {
        return corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CORP_TYPE
     *
     * @param corpType the value for CIS_SENIOR_MANAGER.CORP_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpType(String corpType) {
        this.corpType = corpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CORP_TYPE_DESC
     *
     * @return the value of CIS_SENIOR_MANAGER.CORP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCorpTypeDesc() {
        return corpTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CORP_TYPE_DESC
     *
     * @param corpTypeDesc the value for CIS_SENIOR_MANAGER.CORP_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCorpTypeDesc(String corpTypeDesc) {
        this.corpTypeDesc = corpTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.REGIST_FUND
     *
     * @return the value of CIS_SENIOR_MANAGER.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getRegistFund() {
        return registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.REGIST_FUND
     *
     * @param registFund the value for CIS_SENIOR_MANAGER.REGIST_FUND
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setRegistFund(String registFund) {
        this.registFund = registFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CROP_STATUS
     *
     * @return the value of CIS_SENIOR_MANAGER.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatus() {
        return cropStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CROP_STATUS
     *
     * @param cropStatus the value for CIS_SENIOR_MANAGER.CROP_STATUS
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatus(String cropStatus) {
        this.cropStatus = cropStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CROP_STATUS_DESC
     *
     * @return the value of CIS_SENIOR_MANAGER.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCropStatusDesc() {
        return cropStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CROP_STATUS_DESC
     *
     * @param cropStatusDesc the value for CIS_SENIOR_MANAGER.CROP_STATUS_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCropStatusDesc(String cropStatusDesc) {
        this.cropStatusDesc = cropStatusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.POSITION_TYPE
     *
     * @return the value of CIS_SENIOR_MANAGER.POSITION_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getPositionType() {
        return positionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.POSITION_TYPE
     *
     * @param positionType the value for CIS_SENIOR_MANAGER.POSITION_TYPE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setPositionType(String positionType) {
        this.positionType = positionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.POSITION_TYPE_DESC
     *
     * @return the value of CIS_SENIOR_MANAGER.POSITION_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getPositionTypeDesc() {
        return positionTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.POSITION_TYPE_DESC
     *
     * @param positionTypeDesc the value for CIS_SENIOR_MANAGER.POSITION_TYPE_DESC
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setPositionTypeDesc(String positionTypeDesc) {
        this.positionTypeDesc = positionTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CREATED_BY
     *
     * @return the value of CIS_SENIOR_MANAGER.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CREATED_BY
     *
     * @param createdBy the value for CIS_SENIOR_MANAGER.CREATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.CREATION_DATE
     *
     * @return the value of CIS_SENIOR_MANAGER.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.CREATION_DATE
     *
     * @param creationDate the value for CIS_SENIOR_MANAGER.CREATION_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.LAST_UPDATED_BY
     *
     * @return the value of CIS_SENIOR_MANAGER.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for CIS_SENIOR_MANAGER.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIS_SENIOR_MANAGER.LAST_UPDATE_DATE
     *
     * @return the value of CIS_SENIOR_MANAGER.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIS_SENIOR_MANAGER.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for CIS_SENIOR_MANAGER.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Feb 07 18:55:57 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}