package com.ctc.credit.kernel.model.pengyuan;

import java.util.Date;

public class CreditApply {

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.ID
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.APPLY_NO
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.QUERY_CHANNEL
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private Short queryChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.CREDIT_REPORT_NO
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private String creditReportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.ID_TYPE
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private Short idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.ID_NUMBER
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.PERSON_NAME
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.STATUS
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CREDIT_APPLY.QUERY_STATUS
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    private Short queryStatus;
    
    
    
    private Date  createTime;
    private Date  endTime;
    private Date  updateTime;
    
    

    private String phone; // 申请人的联系电话号码
	private String sbm; // 用户唯一识别码
	private String fsd; // 业务发生地
	private String ywlx; // 业务类型

	private String levelNo; // 被查询者学历证编号
	private String graduateYear; // 被查询者毕业年份
	private String graduateTime; // 被查询者毕业年份，不能为空
	private String college; // 被查询者毕业院校
	private String areaCode; // 行政区划
	
	private String corpName; // 被查询企业名称
	private String orgCode; // 被查询企业组织机构代码
	private String registerNo; // 被查询企业工商注册号
	
	private String queryType; // 查询类型ID
	private String subreportIDs; // 查询的收费子报告类型ID
	private String queryReasonID; // 查询原因ID
	private String distibuteFlag; // 分发标识
	private String refID; // 引用ID
	
	/**聚信立参数 start*/
	//申请人家庭联系人电话
	private String familyTel;
    //工作证明人电话
	private String workTel;
	//申请人的其他联系人电话号码
	private String otherTel;
	//被观察者
	private JuXinLiObservable juXinLiObservable;
	/**聚信立参数 end*/
	
    public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSbm() {
		return sbm;
	}

	public void setSbm(String sbm) {
		this.sbm = sbm;
	}

	public String getFsd() {
		return fsd;
	}

	public void setFsd(String fsd) {
		this.fsd = fsd;
	}

	public String getYwlx() {
		return ywlx;
	}

	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}

	public String getLevelNo() {
		return levelNo;
	}

	public void setLevelNo(String levelNo) {
		this.levelNo = levelNo;
	}

	public String getGraduateTime() {
		return graduateTime;
	}

	public void setGraduateTime(String graduateTime) {
		this.graduateTime = graduateTime;
	}

	public String getGraduateYear() {
		return graduateYear;
	}

	public void setGraduateYear(String graduateYear) {
		this.graduateYear = graduateYear;
	}

	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getCorpName() {
		return corpName;
	}

	public void setCorpName(String corpName) {
		this.corpName = corpName;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getRegisterNo() {
		return registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public String getQueryType() {
		return queryType;
	}

	public void setQueryType(String queryType) {
		this.queryType = queryType;
	}

	public String getSubreportIDs() {
		return subreportIDs;
	}

	public void setSubreportIDs(String subreportIDs) {
		this.subreportIDs = subreportIDs;
	}

	public String getQueryReasonID() {
		return queryReasonID;
	}

	public void setQueryReasonID(String queryReasonID) {
		this.queryReasonID = queryReasonID;
	}

	public String getDistibuteFlag() {
		return distibuteFlag;
	}

	public void setDistibuteFlag(String distibuteFlag) {
		this.distibuteFlag = distibuteFlag;
	}

	public String getRefID() {
		return refID;
	}

	public void setRefID(String refID) {
		this.refID = refID;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.ID
     *
     * @return the value of CREDIT_APPLY.ID
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.ID
     *
     * @param id the value for CREDIT_APPLY.ID
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.APPLY_NO
     *
     * @return the value of CREDIT_APPLY.APPLY_NO
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.APPLY_NO
     *
     * @param applyNo the value for CREDIT_APPLY.APPLY_NO
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.QUERY_CHANNEL
     *
     * @return the value of CREDIT_APPLY.QUERY_CHANNEL
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public Short getQueryChannel() {
        return queryChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.QUERY_CHANNEL
     *
     * @param queryChannel the value for CREDIT_APPLY.QUERY_CHANNEL
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setQueryChannel(Short queryChannel) {
        this.queryChannel = queryChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.CREDIT_REPORT_NO
     *
     * @return the value of CREDIT_APPLY.CREDIT_REPORT_NO
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public String getCreditReportNo() {
        return creditReportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.CREDIT_REPORT_NO
     *
     * @param creditReportNo the value for CREDIT_APPLY.CREDIT_REPORT_NO
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setCreditReportNo(String creditReportNo) {
        this.creditReportNo = creditReportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.ID_TYPE
     *
     * @return the value of CREDIT_APPLY.ID_TYPE
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public Short getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.ID_TYPE
     *
     * @param idType the value for CREDIT_APPLY.ID_TYPE
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setIdType(Short idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.ID_NUMBER
     *
     * @return the value of CREDIT_APPLY.ID_NUMBER
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.ID_NUMBER
     *
     * @param idNumber the value for CREDIT_APPLY.ID_NUMBER
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.PERSON_NAME
     *
     * @return the value of CREDIT_APPLY.PERSON_NAME
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.PERSON_NAME
     *
     * @param personName the value for CREDIT_APPLY.PERSON_NAME
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.STATUS
     *
     * @return the value of CREDIT_APPLY.STATUS
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.STATUS
     *
     * @param status the value for CREDIT_APPLY.STATUS
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CREDIT_APPLY.QUERY_STATUS
     *
     * @return the value of CREDIT_APPLY.QUERY_STATUS
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public Short getQueryStatus() {
        return queryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CREDIT_APPLY.QUERY_STATUS
     *
     * @param queryStatus the value for CREDIT_APPLY.QUERY_STATUS
     *
     * @mbggenerated Tue Dec 23 17:55:35 CST 2014
     */
    public void setQueryStatus(Short queryStatus) {
        this.queryStatus = queryStatus;
    }

	public String getFamilyTel() {
		return familyTel;
	}

	public void setFamilyTel(String familyTel) {
		this.familyTel = familyTel;
	}

	public String getWorkTel() {
		return workTel;
	}

	public void setWorkTel(String workTel) {
		this.workTel = workTel;
	}

	public String getOtherTel() {
		return otherTel;
	}

	public void setOtherTel(String otherTel) {
		this.otherTel = otherTel;
	}
    
    

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public JuXinLiObservable getJuXinLiObservable() {
		return juXinLiObservable;
	}

	public void setJuXinLiObservable(JuXinLiObservable juXinLiObservable) {
		this.juXinLiObservable = juXinLiObservable;
	}

}