package com.ctc.credit.kernel.model.pengyuan;

public class PersonCheckInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.ID
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.CREDIT_REPORT_NO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private String creditReportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.NAME
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.RESULT
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.APPLY_NO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON_CHECK_INFO.PHOTO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.ID
     *
     * @return the value of PERSON_CHECK_INFO.ID
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.ID
     *
     * @param id the value for PERSON_CHECK_INFO.ID
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.CREDIT_REPORT_NO
     *
     * @return the value of PERSON_CHECK_INFO.CREDIT_REPORT_NO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public String getCreditReportNo() {
        return creditReportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.CREDIT_REPORT_NO
     *
     * @param creditReportNo the value for PERSON_CHECK_INFO.CREDIT_REPORT_NO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setCreditReportNo(String creditReportNo) {
        this.creditReportNo = creditReportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.NAME
     *
     * @return the value of PERSON_CHECK_INFO.NAME
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.NAME
     *
     * @param name the value for PERSON_CHECK_INFO.NAME
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.ID_NUMBER
     *
     * @return the value of PERSON_CHECK_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.ID_NUMBER
     *
     * @param idNumber the value for PERSON_CHECK_INFO.ID_NUMBER
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.RESULT
     *
     * @return the value of PERSON_CHECK_INFO.RESULT
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.RESULT
     *
     * @param result the value for PERSON_CHECK_INFO.RESULT
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.APPLY_NO
     *
     * @return the value of PERSON_CHECK_INFO.APPLY_NO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.APPLY_NO
     *
     * @param applyNo the value for PERSON_CHECK_INFO.APPLY_NO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON_CHECK_INFO.PHOTO
     *
     * @return the value of PERSON_CHECK_INFO.PHOTO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON_CHECK_INFO.PHOTO
     *
     * @param photo the value for PERSON_CHECK_INFO.PHOTO
     *
     * @mbggenerated Sat Jan 24 08:29:21 CST 2015
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}