
package com.ctc.credit.shenzhourong.util;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "creditInfoExtWebservice", targetNamespace = "http://webservice.internetfinance.com/", wsdlLocation = "http://www.rongsz.cn:8081/internetfinance/webservice/creditInfoExt?wsdl")
public class CreditInfoExtWebservice
    extends Service
{

    private final static URL CREDITINFOEXTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITINFOEXTWEBSERVICE_EXCEPTION;
    private final static QName CREDITINFOEXTWEBSERVICE_QNAME = new QName("http://webservice.internetfinance.com/", "creditInfoExtWebservice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.rongsz.cn:8081/internetfinance/webservice/creditInfoExt?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITINFOEXTWEBSERVICE_WSDL_LOCATION = url;
        CREDITINFOEXTWEBSERVICE_EXCEPTION = e;
    }

    public CreditInfoExtWebservice() {
        super(__getWsdlLocation(), CREDITINFOEXTWEBSERVICE_QNAME);
    }

    public CreditInfoExtWebservice(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITINFOEXTWEBSERVICE_QNAME, features);
    }

    public CreditInfoExtWebservice(URL wsdlLocation) {
        super(wsdlLocation, CREDITINFOEXTWEBSERVICE_QNAME);
    }

    public CreditInfoExtWebservice(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITINFOEXTWEBSERVICE_QNAME, features);
    }

    public CreditInfoExtWebservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditInfoExtWebservice(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICreditInfoExtWebservice
     */
    @WebEndpoint(name = "CreditInfoExtWebservicePort")
    public ICreditInfoExtWebservice getCreditInfoExtWebservicePort() {
        return super.getPort(new QName("http://webservice.internetfinance.com/", "CreditInfoExtWebservicePort"), ICreditInfoExtWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICreditInfoExtWebservice
     */
    @WebEndpoint(name = "CreditInfoExtWebservicePort")
    public ICreditInfoExtWebservice getCreditInfoExtWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.internetfinance.com/", "CreditInfoExtWebservicePort"), ICreditInfoExtWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITINFOEXTWEBSERVICE_EXCEPTION!= null) {
            throw CREDITINFOEXTWEBSERVICE_EXCEPTION;
        }
        return CREDITINFOEXTWEBSERVICE_WSDL_LOCATION;
    }

}
