
package com.ctc.credit.shenzhourong.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICreditInfoExtWebservice", targetNamespace = "http://webservice.internetfinance.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICreditInfoExtWebservice {


    /**
     * 
     * @param requestParameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryServiceItemByCode", targetNamespace = "http://webservice.internetfinance.com/", className = "com.ctc.credit.shenzhourong.util.QueryServiceItemByCode")
    @ResponseWrapper(localName = "queryServiceItemByCodeResponse", targetNamespace = "http://webservice.internetfinance.com/", className = "com.ctc.credit.shenzhourong.util.QueryServiceItemByCodeResponse")
    public String queryServiceItemByCode(
        @WebParam(name = "requestParameter", targetNamespace = "")
        String requestParameter);

}
